apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: text-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: apache/spark:3.5.1
          command:
            - /bin/bash
            - -c
            - /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/spark--org.apache.spark.deploy.worker.Worker*.out
          env:
            - name: SPARK_WORKER_MEMORY
              value: "1g"
            - name: SPARK_WORKER_CORES
              value: "2"
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1500m"
