apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming
  namespace: text-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      containers:
        - name: spark-streaming
          image: vn-text-search/spark-jobs:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_JOB
              value: "streaming_indexer.py"
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRET_KEY
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
