#-------------------------
# services/api/Dockerfile
FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY main.py .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

#-------------------------
# services/crawler/Dockerfile
FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "vnexpress_crawler.py"]
#----------------------------------
# services/frontend/Dockerfile
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

#-------------------------------
# services/spark-jobs/Dockerfile
FROM apache/spark:3.5.1
USER root

RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    elasticsearch==8.13.0 \
    boto3==1.34.0 \
    underthesea==6.8.4

WORKDIR /opt/spark-jobs
COPY streaming_indexer.py .
COPY spark_session.py .
COPY udfs.py .

ENV SPARK_MASTER=local[2]
ENV SPARK_JOB=streaming_indexer.py
ENV PATH="/opt/spark/bin:${PATH}"

ENTRYPOINT ["/opt/spark/bin/spark-submit", \
  "--master", "local[2]", \
  "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4"]

CMD ["/opt/spark-jobs/streaming_indexer.py"]

